routes/web.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('users', UserController::class)->middleware('login')->except(['show']);

Route::get('login', function() {
    return view('user.login');
})->name('user.login');

Route::post('login', [UserController::class, 'login'])->name('users.login');

Route::get('/', function() {
    return redirect(route('user.login'));
});

Route::post('/', [UserController::class, 'logout'])->name('user.logout');

Route::get('user/{id}/profile', [UserController::class, 'profile'])->name('user.profile')->middleware('login');

Route::put('user/{id}/profile', [UserController::class, 'updatePassword'])->name('user.updatePassword');

Route::get('remember', function() {
    return view('user.reset-password');
})->name('user.remember');

Route::post('remember', [UserController::class, 'createToken'])->name('user.createToken');

Route::get('remember/{email}', function() {
    return view('user.reset-token');
})->name('user.token');

Route::post('remember/{email}', [UserController::class, 'resetPassword'])->name('user.confirmToken');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use App\Mail\RememberPassword;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class User extends Model
{
    use HasFactory;

    public function scopeSoftDelete($query)
    {
        return $query->whereNull('deleted_at');
    }

    public function login($request)
    {
        $user = User::softDelete()
            ->where('email', $request->email)
            ->first();
        if (empty($user)) {
            session()->flash('message', 'Địa chỉ email hoặc mật khẩu không chính xác');
            return false;
        } else {
            if (Hash::check($request->password, $user->password)) {
                session(['id' => $user->id]);
                return true;
            }
            session()->flash('message', 'Địa chỉ email hoặc mật khẩu không chính xác');
            return false;
        }
    }

    public function register($request)
    {
        $user = new User();
        $user->email = $request->email;
        $user->userName = $request->userName;
        $user->address = $request->address;
        $user->password = bcrypt($request->password);
        $user->save();
        session()->flash('message', 'Đăng kí tài khoản thành công!');
    }

    public function getAllUsers()
    {
        return User::softDelete()->orderBy('updated_at', 'DESC')->paginate(6);
    }

    public function getUser($id)
    {
        return User::find($id);
    }

    public function updateUser($request, $id)
    {
        $user = User::find($id);
        $path = null;
        if ($request->file('avatar') != null) {
            $path = $request->file('avatar')->store('public');
        }
        if ($path != null) {
            $user->avatar = $path;
        }
        $user->userName = $request->userName;
        $user->address = $request->address;
        $user->save();
        session()->flash('message', 'Cập nhật thông tin thành công!');
    }

    public function deleteUser($id)
    {
        $user = User::find($id);
        $user->deleted_at = now();
        if ($user->avatar != null) {
            Storage::delete($user->avatar);
            $user->avatar = null;
        }
        $user->save();
        session()->flash('message', 'Xóa thông tin thành công!');
    }

    public function updatePassword($request)
    {
        $user = User::find(session('id'));
        $user->password = bcrypt($request->password);
        $user->save();
        session()->flash('message', 'Thay đổi mật khẩu thành công!');
    }

    public function createToken($request)
    {
        $user = User::where('email', $request->email)->softDelete()->first();
        if (!empty($user)) {
            $token = random_int(100000, 999999);
            $user->reset_password_token = $token;
            $user->expired_time = now()->addMinutes(10);
            $user->save();
            $mess = "Mã xác thực quên mật khẩu của bạn là $token. Mã này có hiệu lực trong 10 phút.";
            Mail::to($request->email)->send(new RememberPassword($mess));
        }
    }

    public function resetPassword($request, $email)
    {
        $user = User::where('email', $email)->softDelete()->first();
        if (!empty($user)) {
            if ($user->reset_password_token == $request->reset_password_token && $user->expired_time >= now()) {
                $newPassword = Str::random(6);
                $user->password = bcrypt($newPassword);
                $user->expired_time = now();
                $user->save();
                $mess = "Mật khẩu của bạn là: $newPassword. Vui lòng bảo mật thông tin này.";
                Mail::to($request->email)->send(new RememberPassword($mess));
                session()->flash('message', 'Mật khẩu đã được gửi tới email của bạn.');
            } else {
                session()->flash('message', 'Mã xác thực không chính xác hoặc đã hết hạn.');
            }
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use Illuminate\Http\Request;
use App\Http\Requests\LoginRequest;
use App\Http\Requests\RememberEmailRequest;
use App\Http\Requests\RememberTokenRequest;
use App\Http\Requests\UpdatePasswordRequest;
use App\Http\Requests\UpdateUserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = app('user')->getAllUsers();
        return view('user.index', ['users' => $users]);
    }

    //Login
    public function login(LoginRequest $request)
    {
        if (app('user')->login($request)) {
            return redirect()->route('users.index');
        }
        return redirect()->back()->withInput();
    }

    //Logout
    public function logout()
    {
        session()->forget('id');
        return redirect(route('user.login'));
    }

    //Profile
    public function profile($id)
    {
        $data = app('user')->getUser($id);
        return view('user.profile', ['user' => $data]);
    }

    //Update password
    public function updatePassword(UpdatePasswordRequest $request)
    {
        app('user')->updatePassword($request);
        return redirect()->route('users.index');
    }

    //Create token
    public function createToken(RememberEmailRequest $request)
    {  
        app('user')->createToken($request);
        return redirect()->route('user.token', $request->email);
    }

    //Reset password
    public function resetPassword(RememberTokenRequest $request, $email)
    {    
        app('user')->resetPassword($request, $email);
        return redirect()->route('user.token', $email);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        app('user')->register($request);
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = app('user')->getUser($id);
        return view('user.edit', ['user' => $data]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        app('user')->updateUser($request, $id);
        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        app('user')->deleteUser($id);
        return redirect()->route('users.index');
    }
}

resources/views/user/edit.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="form">
            <form action="{{route('users.update', $user->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <h2 class="text-primary" align="center">Sửa thông tin tài khoản</h2>
                <div class="form-group">
                    <label for="avatar">Ảnh đại diện:</label><br>
                    <input type="file" name="avatar">
                    @error('avatar')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="userName">Tên người dùng:</label>
                    <input type="text" class="form-control" placeholder="Tên người dùng" name="userName" value="{{old('userName') ? old('userName') : $user->userName}}">
                    @error('userName')
                        <p class="text-danger">{{$message}}</p>
                     @enderror
                </div>
                <div class="form-group">
                    <label for="address">Địa chỉ:</label>
                    <input type="text" class="form-control" placeholder="Nhập địa chỉ" name="address" value="{{old('address') ? old('address') : $user->address}}">
                    @error('address')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group float-sm-right">
                    <input type="submit" value="Hoàn tất" class="btn btn-primary">
                    <a href="{{route('users.index')}}" class="btn btn-danger">Hủy</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layout.app')
@section('content')
    <form method="POST" action="{{route('user.logout')}}">
        @csrf
        @method('POST')
        <div class="float-right">
            <a href="{{route('user.profile', session('id'))}}">Thông tin cá nhân</a>
            <input type="submit" value="Đăng xuất" class="btn btn-danger">
        </div>
        <a href="{{route('users.create')}}" class="btn btn-primary">Đăng kí</a>
    </form>
    @if(session()->has('message'))
        <p class="text-success">{{session('message')}}</p>
    @endif
    <table class="table table-striped">
        <h1 class="text-primary" align="center">Danh sách người dùng</h1>
        <thead>
            <tr>
                <th>STT</th>
                <th>Ảnh đại diện</th>
                <th>Email</th>
                <th>Tên người dùng</th>
                <th>Địa chỉ</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>{{$loop->index + 1}}</td>
                    @if($user->avatar == null)
                        <td><img src="avatar.jpg" width="40px" height="40px"></td>
                    @else
                        <td><img src="{{Storage::url($user->avatar)}}" width="40px" height="40px"></td>
                    @endif
                    <td>{{$user->email}}</td>
                    <td>{{$user->userName}}</td>
                    <td>{{$user->address}}</td>
                    <td>
                        <form method="POST" action="{{route('users.destroy', $user->id)}}">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('users.edit', $user->id)}}" class="btn btn-primary">Sửa</a>
                            <input type="submit" value="Xóa" class="btn btn-danger">
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div style="display: flex; justify-content: center;">
        {{$users->links('pagination::bootstrap-4')}}
    </div>
@endsection

resources/views/user/login.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="form">
            <form method="POST" action="{{route('users.login')}}">
                @csrf
                @method('POST')
                <h2 class="text-primary" align="center">Đăng nhập hệ thống</h2>
                <div class="form-group">
                    <label for="email">Địa chỉ email:</label>
                    <input type="text" class="form-control" placeholder="Nhập địa chỉ email" name="email" value="{{old('email')}}">
                    @error('email')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="pwd">Mật khẩu:</label>
                    <input type="password" class="form-control" placeholder="Nhập mật khẩu" name="password">
                    @error('password')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <input type="submit" value="Đăng nhập" class="btn btn-primary btn-block">
                    @if(session()->has('message'))
                        <p class="text-danger">{{session('message')}}</p>
                    @endif
                </div>
                <div class="form-group">
                    <a href="{{route('user.remember')}}">Quên mật khẩu</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/profile.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="form">
            <form action="{{route('users.update', $user->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <h2 class="text-primary" align="center">Sửa thông tin tài khoản</h2>
                <div class="form-group">
                    <label for="avatar">Ảnh đại diện:</label><br>
                    <input type="file" name="avatar">
                    @error('avatar')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="userName">Tên người dùng:</label>
                    <input type="text" class="form-control" placeholder="Tên người dùng" name="userName" value="{{old('userName') ? old('userName') : $user->userName}}">
                    @error('userName')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="address">Địa chỉ:</label>
                    <input type="text" class="form-control" placeholder="Nhập địa chỉ" name="address" value="{{old('address') ? old('address') : $user->address}}">
                    @error('address')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group float-sm-right">
                    <input type="submit" value="Hoàn tất" class="btn btn-primary">
                    <a href="{{route('users.index')}}" class="btn btn-danger">Hủy</a>
                </div>
            </form>
        </div>
        <div class="form">
            <form method="POST" action="{{route('user.updatePassword', $user->id)}}">
                @csrf
                @method('PUT')
                <h2 class="text-primary" align="center">Đổi mật khẩu</h2>
                <div class="form-group">
                    <label for="password">Mật khẩu:</label>
                    <input type="password" class="form-control" placeholder="Mật khẩu" name="password">
                    @error('password')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password_confirmation">Xác nhận mật khẩu:</label>
                    <input type="password" class="form-control" placeholder="Xác nhận mật khẩu" name="password_confirmation">
                    @error('password_confirmation')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group float-sm-right">
                    <input type="submit" value="Lưu" class="btn btn-primary">
                    <a href="{{route('users.index')}}" class="btn btn-danger">Hủy</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/register.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="form">
            <form method="POST" action="{{route('users.store')}}">
                @csrf
                @method('POST')
                <h2 class="text-primary" align="center">Đăng kí tài khoản</h2>
                <div class="form-group">
                    <label for="email">Địa chỉ email:</label>
                    <input type="text" class="form-control {{$errors->has('email') ? 'input-error' : ''}}" placeholder="Nhập địa chỉ email" name="email" value="{{old('email')}}">
                    @error('email')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="userName">Tên người dùng:</label>
                    <input type="text" class="form-control {{$errors->has('userName') ? 'input-error' : ''}}" placeholder="Tên người dùng" name="userName" value="{{old('userName')}}">
                    @error('userName')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="address">Nhập địa chỉ:</label>
                    <input type="text" class="form-control {{$errors->has('address') ? 'input-error' : ''}}" placeholder="Nhập địa chỉ" name="address" value="{{old('address')}}">
                    @error('address')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password">Mật khẩu:</label>
                    <input type="password" class="form-control {{$errors->has('password') ? 'input-error' : ''}}" placeholder="Mật khẩu" name="password">
                    @error('password')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="password_confirmation">Xác nhận mật khẩu:</label>
                    <input type="password" class="form-control {{$errors->has('password_confirmation') ? 'input-error' : ''}}" placeholder="Xác nhận mật khẩu" name="password_confirmation">
                    @error('password_confirmation')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group float-sm-right">
                    <input type="submit" value="Hoàn tất" class="btn btn-primary">
                    <a class="btn btn-danger" href="{{route('users.index')}}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/reset-password.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="form">
            <form method="POST" action="#">
                @csrf
                @method('POST')
                <h2 class="text-primary" align="center">Quên mật khẩu</h2>
                <div class="form-group">
                    <label for="email">Địa chỉ email:</label>
                    <input type="text" class="form-control" placeholder="Nhập địa chỉ email" name="email" value="{{old('email')}}">
                    @error('email')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group float-right">
                    <input type="submit" value="Gửi mã xác thực" class="btn btn-primary">
                    <a href="{{route('user.login')}}" class="btn btn-danger">Quay lại</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/user/reset-token.blade.php
@extends('layout.app')
@section('content')
    <div class="container">
        <div class="form">
            <form method="POST" action="#">
                @csrf
                @method('POST')
                <h2 class="text-primary" align="center">Quên mật khẩu</h2>
                <div class="form-group">
                    <label for="reset_password_token">Nhập mã xác thực:</label>
                    <input type="text" class="form-control" placeholder="Nhập mã xác thực" name="reset_password_token" value="{{old('reset_password_token')}}">
                    @error('reset_password_token')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                    @if(session()->has('message'))
                        <p class="text-danger">{{session('message')}}</p>
                    @endif
                </div>
                <div class="form-group float-right">
                    <input type="submit" value="Lấy mật khẩu" class="btn btn-primary">
                    <a href="{{route('user.login')}}" class="btn btn-danger">Về trang đăng nhập</a>
                </div>
            </form>
        </div>
    </div>
@endsection